name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ha-test-plugin: ["0.13.354", "0.13.366"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements-dev.txt
      - run: pip install pytest-homeassistant-custom-component==${{ matrix.ha-test-plugin }}
      - run: ruff check .
      - run: pytest
